### ISSUE TITLE
[FocusNotifications] Build error

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-notifications#22]
# Actual behaviour

When the FocusNotifications component is used like below 

``` javascript
<FocusNotifications />
```

It raised errors.
But when  it is used like this : 

``` javascript
<FocusNotifications.default />
```

It works.
# Expected behaviour

``` javascript
<FocusNotifications />
```
# Versions

0.1.0-rc1

**Comment by pierr** [comment]
This will be fixed by the `webpack-focus` upgrade
