### ISSUE TITLE
[Empty response] Error if the server response is empty

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-notifications#23]

**Comment by pierr** [comment]
@JoanaDalmeida Can you provide more context on the error ? Where does it breaks?
Is it on `response.json()` call or after in the `Promise` ?

**Comment by pierr** [comment]
cc @pierbrisson

**Comment by JoanaDalmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/3300779/12415222/c781e0cc-be9a-11e5-8052-a5d85c3dd8d6.png)

**Comment by DT-KleeGroup** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue.

Thank you!
