### ISSUE TITLE
[Enhancement] Close notification drawer on outside click

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-notifications#24]
# Current behavior

when the notification drawer is open, currently the only way to close it is for the user to click on the "X" at the top right.
# Expected behavior

Like all drawers in Focus applications, if the user clicks outside of the drawer, it should close itself.

**Comment by pierr** [comment]
As in the major OS:  `OSX`  and the other OS such as `w10` the notification center is not closed on a click outside.
I want the opinion of @Bernardstanislas , @Tommass , @nadege-focus before doing it.

**Comment by TomGallon** [comment]
done in https://github.com/get-focus/focus-notifications/pull/56
