### ISSUE TITLE
[Enhancement] Differenciate more clearly the title of a notification from its description

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-notifications#31]
# Current behaviour

It is somewhat difficult to quickly and easily differenciate a notification's title from its description and one notification from an other.

![image](https://cloud.githubusercontent.com/assets/8983628/12200625/3db56da0-b620-11e5-92a6-03c160b12fe4.png)
# Expected behaviour

Improve the styling to differenciate more clearly the title from the description.  Either via a play on the font weight/size/style, color, opacity, background color, etc...

And add a distinct seperation between notifications

A few examples:

![image](https://cloud.githubusercontent.com/assets/8983628/12200833/4d32d24e-b621-11e5-8380-deb0f09a549f.png)

![image](https://cloud.githubusercontent.com/assets/8983628/12200782/0665a472-b621-11e5-97af-6e3a7e2075f6.png)

![image](https://cloud.githubusercontent.com/assets/8983628/12200949/cb09a9d6-b621-11e5-88a4-3e649e92282f.png)

![image](https://cloud.githubusercontent.com/assets/8983628/12200986/04585a98-b622-11e5-931a-46a7f544fa66.png)

lots of examples here http://www.smashingapps.com/2015/01/20/45-free-popup-alert-window-notification-photoshop-designs.html

**Comment by pierr** [comment]
![main](https://cloud.githubusercontent.com/assets/286966/12450364/9f344044-bf83-11e5-847c-8244cacea26e.png)
Android notifs
