### ISSUE TITLE
[Enhancement] Display more clearly the "Done/Clear notifications" button on the Day line

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-notifications#32]
# Current behaviour

The button at the end of the Day line ("Today", "Week") allowing the clearing of that day's/week's notifications is barely visible.

![image](https://cloud.githubusercontent.com/assets/8983628/12205016/418abfc6-b638-11e5-8cea-f4054c9ac5be.png)
# Expected behaviour

Make it stand out more by putting it in a visible color

**Comment by pierr** [comment]
It was due to a `CSS` default override
