### ISSUE TITLE
[Enhancement] Remove double scroll when lots of notifications are present on a long page

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-notifications#33]
# Current behaviour

When there are many notifications in the Notification Center, a scrollbar appears.
But when the page on which the user finds himself already has a scrollbar, the dreaded double scroll rears its ugly head!

![image](https://cloud.githubusercontent.com/assets/8983628/12205098/e3c8c116-b638-11e5-8e73-0ee304f3a03c.png)
# Expected behaviour

Death to the double scroll!!!

**Comment by TomGallon** [comment]
problems resolved in focus-application.
