### ISSUE TITLE
Notification timestamp is one hour in the future

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-notifications#34]
# Current behaviour

When a new notification is created and shows up in the Notification Center, its datetime is one hour in the future rather than "A second ago/Just now/..."
# Expected behaviour

As awesome as it would be to be in the future, display the correct timestamp.

**Comment by pierr** [comment]
@pierbrisson I think this issue is related to your API config.

**Comment by pierr** [comment]
`moment` should be configured with your timezone.
http://momentjs.com/

**Comment by pierr** [comment]
http://momentjs.com/timezone/
