### ISSUE TITLE
Z-index when buttons on screen in header

### ISSUE THREAD

**Issue by pierbrisson** [KleeGroup/focus-notifications#35]
# Current behavior

When scrolling down a page with action buttons which then move back up into the header, the buttons come to the forefront instead of staying behind the notifications panel

![image](https://cloud.githubusercontent.com/assets/8983628/12262403/0459d900-b928-11e5-80a7-17bfeda0d82b.png)
# Expected behavior

Have the notifications panel only in the forefront

**Comment by pierr** [comment]
I will add a `zIndex` as props of the component and add a default value to `16777271` according to http://www.puidokas.com/max-z-index/
