### ISSUE TITLE
[Bug] error appearing when session expired

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-notifications#43]
# Current behaviour

When I don't log off and my session expires, I get errors on the page (the big red thing on the lower right corner) stating the following :
Uncaught Error: NOTIFICATION_LIST reducer : action RECEIVE_NOTIFICATIONS : the payload is not a(n) array it is : {"globalErrors":["Session has expired"]}

![image](https://cloud.githubusercontent.com/assets/14293391/13637018/4c7ee662-e605-11e5-9df0-343ec791b013.png)

Plus lots of 403 in the console : 
![image](https://cloud.githubusercontent.com/assets/14293391/13637045/817361ea-e605-11e5-82a3-f0623b800e70.png)
# Expected behaviour

When the session is expired, there should be no polling for notifs. 
Either add a session length in Focus (too complicated for the purpose) or accept that answer and from the moment you receive it :
1) don't display it 
2) stop polling from the moment you receive it till next logon
## Versions

Focus-core: 0.12.4
Focus-components: 0.8.6
Focus-notifications: 0.2.0-rc6 (mmm, there is a rc on prod)

**Comment by DT-KleeGroup** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue.

Thank you!
