### ISSUE TITLE
Redirect when click on remove

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/focus-notifications#51]
When we click on remove notification, the global click is triggered.

**Comment by TomGallon** [comment]
not reproduced. Seems to be corrected with the graphics corrections

**Comment by DT-KleeGroup** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue.

Thank you!
