### ISSUE TITLE
Unexpected end of JSON input when deleting a notification

### ISSUE THREAD

**Issue by tadam75** [KleeGroup/focus-notifications#70]
Hello,

When I delete a notification, this error happens : 

![image](https://cloud.githubusercontent.com/assets/14274196/24396114/6261dcde-13a2-11e7-8a57-68dfecbcb155.png)

I think it comes from here, because now the server returns an "empty" response : 
https://github.com/get-focus/focus-notifications/blob/develop/src/actions/delete-notification.js#L47

**Comment by Hartorn** [comment]
Corrected in 0.4.1
